name: PlayerDeathLocations
version: 2
main: me.zachbears27.DeathLocation
description: Player Death Locations
author: A_Brave_Panda
commands:
    death:
        aliases: [de]
        description: Find a players death!
        usage: 
          /<command>
